name: twist_rna
channels:
  - bioconda
  - conda-forge
dependencies:
#  - python=3.6
#  - samtools=1.9
#  - arriba=2.1.0
  - star-fusion=1.9.1
#  - fusioncatcher=1.30
#  - fastqc=0.11.8
#  - multiqc=1.9
#  - rseqc=4.0.0
#  - picard=2.25.0
#  - picard=2.10.6

#  - bcftools=1.11
#  - pysam=0.16.0.1
#  - pandas=1.2.1
#  - bamtools=2.5.1
#  - parallel=20190522
#  - bedtools=2.29
#  - sed=4.7
#  - snakemake-wrapper-utils=0.1.3
#  - gatk4=4.1.9.0
#  - vt=2015.11.10
