name: gms_somatic
channels:
  - bioconda
  - conda-forge
dependencies:
   - bamtools=2.5.1
   - bcbio-variation-recall=0.2.6
   - bcftools=1.11
   - bedtools=2.29
   - biobambam=2.0.87
   - bwa=0.7.17
   - cnvkit=0.9.8
   - cutadapt=3.2
   - fastqc=0.11.8
   - fastp=0.20.1
   - fgbio=1.0.0
   - freebayes=1.3.2
   - gatk4=4.1.9.0
   - genefuse=0.6.1
   - gridss=2.10.2
   - msisensor-pro=1.1.a
   - multiqc=1.9
   - pandas=1.2.1
   - parallel=20190522
   - picard=2.25.0
   - pysam=0.16.0.1
   - python=3.7
   - samtools=1.11
   - sed=4.7
   - snakemake-wrapper-utils=0.1.3
   - umis=1.0.7
   - vardict-java=1.8.2
   - varscan=2.4.3-0
   - vt=2015.11.10
  #  - ensembl-vep=103.1
